### ISSUE TITLE
MLM bluetooth found but not connected

### ISSUE THREAD

**Issue by folmdad83** [Duwaynef/MLM2PRO-BT-APP#4]
LM monitor shows up but not connected to the program. I have a bluetooth sign and another what looks like monitor sign. I have uninstalled program multiple times and have the same issue. Its like its connected but won't actually connect.

**Comment by FastFarming** [comment]
I had a similar problem, make sure your mobile device that you use too authenticate awesome golf is connected to the MLM2PRO. That's what fixed it for me..

**Comment by Calvert86** [comment]
Same problem worked perfectly first day now bluetooth signal shows up in connector but wont connect to device. When i go to bluetooth menu on windows it sees the device but wont allow me to connect....just shows try connecting your device again.

**Comment by Duwaynef** [comment]
You wont be able to directly connect to the mlm2pro with windows etc as it expects a very sepecific sequence of events to allow a connection. any connection directly to windows will immedately just get disconnected.

if the device is paired with windows, just make sure that the light on the device is solid red before you open my connector.

after you authorize awesome golf you have to close the rapsodo app so that the device goes back to solid red.

**Comment by folmdad83** [comment]
Thanks! I figured it out last night it was my Bluetooth connecter I had a 4.0 and then with the new one I got I still needed it to be placed very close to the mlm no issues! thank you very much for figuring out this direct connection! It’s amazing!Sent from my iPhoneOn Apr 4, 2024, at 7:54 AM, Duwayne ***@***.***> wrote:﻿
You wont be able to directly connect to the mlm2pro with windows etc as it expects a very sepecific sequence of events to allow a connection. any connection directly to windows will immedately just get disconnected.
if the device is paired with windows, just make sure that the light on the device is solid red before you open my connector.
after you authorize awesome golf you have to close the rapsodo app so that the device goes back to solid red.
